config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: %i[index show edit update new create destroy]
  resources :bookmarks, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment,
            length: { minimum: 6 }
  validates :movie,
            uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies,
           through: :bookmarks,
           dependent: :destroy
  validates :name,
            presence: true,
            uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title,
            presence: true,
            uniqueness: true
  validates :overview,
            presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list_id), status: :see_other
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy edit update]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    movie = Movie.find(params[:movie_id])
    @list.movies = movie
    raise
    if @list.save
      redirect_to lists_path, status: :see_other
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    if @list.save
      redirect_to lists_path
    else
      redirect_to edit_list_path(@list), status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def int_to_stars(int, total)
    # a => quotient - whole stars
    # b => remainder - part stars
    a, b = int.divmod(1)
    c = total - (a + b).ceil
    # FA icons
    star_filled = '<i class="fa-solid fa-star star"></i>'
    star_half = '<i class="fa-solid fa-star-half-stroke star"></i>'
    star_empty = '<i class="fa-regular fa-star star"></i>'
    # html output
    html_result = []
    # add filled stars
    a.times do
      html_result << star_filled
    end
    # add half star if needed
    html_result << star_half unless b.nil? || b.zero?
    # add empty stars
    c.times do
      html_result << star_empty
    end
    html_result.join.html_safe
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add new movie to <em><%= @list ? @list.name.capitalize : "list" %></em></h1>
  <p><%= link_to "back to all lists", lists_path, class: "btn btn-info" %></p>
  <%= render 'shared/bookmarks/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="m-3">
  <h1>Add new list</h1>
  <p><%= link_to "back to all lists", lists_path, class: "btn btn-info" %></p>
  <div class="m-5"><%= render 'shared/lists/upload_cover' %></div>
</div>

app/views/lists/index.html.erb
<div class="container">

  <div class="row justify-content-center">
    <% @lists.each do |list| %>
      <%= render "shared/lists/card", list: list %>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<div class="m-3">
  <h1>Add new list</h1>
  <p><%= link_to "back to all lists", lists_path, class: "btn btn-info" %></p>
  <small class="text-warning">*Not 100% working!!!</small>
  <div class="m-5"><%= render 'shared/lists/form' %></div>
</div>

app/views/lists/show.html.erb
<div class="m-0 pt-3 pe-3 ps-3 d-flex align-items-center sticky-list-navbar">
  <div class="col">
    <h1 class="me-5"><%= @list.name %></h1>
    <p><%= link_to "back to all lists", lists_path, class: "btn btn-info" %></p>
  </div>
  <p>
    <%= link_to "+ movie", new_bookmark_path(list_id: @list.id), class: "btn btn-info col" %>
    <%= link_to @list.photo.attached? ? "edit photo" : "add photo", edit_list_path(@list), class: "btn btn-info col" %>
  </p>
</div>

<div class="me-3 ms-3 mt-3">
  <% @list.movies.each do |movie| %>
    <%= render 'shared/movies/card-lewagon', movie: movie %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top">
  <h1><%= link_to "Your Watch List", root_path %></h1>
  <ul class="list-inline">
    <li class="nav-item">
      <%= link_to "Create new list", new_list_path %>
    </li>
  </ul>
</div>

app/views/shared/bookmarks/_form.html.erb
<%= simple_form_for [@bookmark] do |f| %>
  <%= f.input :comment, :label => "Bookmark comment" %>
  <%= f.association :list, selected: (@list ? @list.id : 1) %>
  <%= f.association :movie %>
  <%= f.submit "Create bookmark" %>
<% end %>

app/views/shared/lists/_card.html.erb
<div class="card border-light bg-transparent m-3 col-12 col-sm-6 col-lg-3 ">
  <%= link_to list_path(list) do %>
    <% if list.photo.attached? %>
      <%= cl_image_tag list.photo.key, class: "card-img" %>
    <% else %>
      <%= image_tag list.movies.sample.poster_url, class: "card-img" %>
    <% end %>
    <p class="card-img-overlay card-title text-center"><%= list.name %></p>
  <% end %>
</div>

app/views/shared/lists/_form.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name, :label => "Watch List Name" %>
  <%= f.submit "Create List" %>
<% end %>

app/views/shared/lists/_form.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name, label: "List name" %>
  <%= f.input :photo, as: :file, label: 'List cover photo'  %>
  <%= f.submit "Create List" %>
<% end %>

app/views/shared/lists/_upload_cover.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name, label: "Current list name" %>
  <%= f.input :photo, as: :file, label: 'List cover photo'  %>
  <%= f.submit "Update List" %>
<% end %>

app/views/shared/movies/_card-lewagon.html.erb
<div class="card-product mb-3">
  <%= image_tag movie.poster_url %>
  <div class="card-product-infos">
    <h2><%= movie.title %></h2>
    <p><%= movie.overview %></p>
    <p><%= int_to_stars(movie.rating/10,10) %> (<%= movie.rating %>%)</p>
    <p><em><i class="fa-solid fa-quote-left"></i> <%= movie.bookmarks.sample.comment %> <i class="fa-solid fa-quote-right"></i></em></p>
  </div>
</div>

app/views/shared/movies/_card.html.erb
<div class="d-flex">

  <%= image_tag movie.poster_url %>
  <div>
    <h5>
      <%= movie.title %>
    </h5>

    <p>
      <%= movie.overview %>
    </p>

    <p>
      <%= movie.rating %>
    </p>
  </div>

</div>